name: Bump Version

on:
  push:
    branches:
      - master

jobs:
  bump-version:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16.x'
      
      - name: Git config
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
      
      - name: Bump version
        run: npm version patch -m "🔖 버전 업데이트: %s"
      
      - name: Push changes
        run: git push --follow-tags
      
      - name: Archive repository
        run: |
          cp -r . /tmp/src
          cd /tmp
          tar -czf src.tar.gz src
      
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: src
          path: /tmp/src.tar.gz
          retention-days: 1 